Repository pt807/spring-boot-groupirum, pull requests merged in 2022-08, with the labels that each got.

#27 feat: 댓글 수정, 답글 오류 수정
  src/main/resources/static/js/view.js
  src/main/resources/templates/recruitView.html
  src/main/resources/templates/replyList.html
Labels: bug, frontend

#32 feat: 메인 페이지 무한 스크롤 기능 구현
  src/main/java/com/green/groupirum/controller/HomeController.java
  src/main/java/com/green/groupirum/service/RecruitService.java
  src/main/resources/db/h2/data.sql
  src/main/resources/static/js/index.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/recruitCard.html
  src/main/resources/templates/recruitView.html
Labels: frontend, backend, feature

#33 feat: 사용자 마이페이지 기능 구현
  .gitignore
  src/main/java/com/green/groupirum/controller/MemberController.java
  src/main/java/com/green/groupirum/domain/Member.java
  src/main/java/com/green/groupirum/domain/Recruit.java
  src/main/java/com/green/groupirum/domain/Reply.java
  src/main/java/com/green/groupirum/dto/MemberDto.java
  src/main/java/com/green/groupirum/dto/MemberUpdateRequestDto.java
  src/main/java/com/green/groupirum/repository/MemberRepository.java
  src/main/java/com/green/groupirum/repository/RecruitRepository.java
  src/main/java/com/green/groupirum/repository/ReplyRepository.java
  src/main/java/com/green/groupirum/service/FileService.java
  src/main/java/com/green/groupirum/service/MemberService.java
  src/main/java/com/green/groupirum/service/RecruitService.java
  src/main/java/com/green/groupirum/service/ReplyService.java
  src/main/resources/application.yml
  src/main/resources/db/h2/schema.sql
  src/main/resources/static/css/memberRecruits.css
  src/main/resources/static/css/memberReplies.css
  src/main/resources/static/css/memberUpdateForm.css
  src/main/resources/static/css/myPage.css
  src/main/resources/static/images/profile_image_default.png
  src/main/resources/static/js/memberUpdateForm.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/memberRecruits.html
  src/main/resources/templates/memberReplies.html
  src/main/resources/templates/memberUpdateForm.html
  src/main/resources/templates/myPage.html
  src/main/resources/templates/recruitView.html
  src/main/resources/templates/replyList.html
Labels: frontend, backend, feature

#34 design: css 스타일 수정
  src/main/resources/static/css/recruitView.css
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/join.html
Labels: frontend

#35 feat: 메인 페이지 필터 기능 추가
  src/main/java/com/green/groupirum/controller/HomeController.java
  src/main/java/com/green/groupirum/controller/RecruitController.java
  src/main/java/com/green/groupirum/repository/RecruitRepository.java
  src/main/java/com/green/groupirum/service/RecruitService.java
  src/main/resources/static/css/contact.css
  src/main/resources/static/css/nicepage.css
  src/main/resources/static/js/index.js
  src/main/resources/templates/index.html
  src/main/resources/templates/recruit.html
  src/main/resources/templates/recruitUpdate.html
Labels: frontend, backend, feature

#37 글 작성, 수정, 상세보기 페이지 수정
  src/main/resources/templates/recruit.html
  src/main/resources/templates/recruitUpdate.html
  src/main/resources/templates/recruitView.html
  src/main/resources/templates/replyList.html
Labels: frontend

#41 fix: 반응형 페이지 에러 수정
  src/main/resources/static/css/contact.css
  src/main/resources/static/css/memberUpdateForm.css
  src/main/resources/static/js/index.js
  src/main/resources/templates/memberUpdateForm.html
  src/main/resources/templates/recruitView.html
Labels: bug, frontend
