Repository pt807/spring-boot-groupirum, pull requests merged in 2022-07, with the labels that each got.

#11 feat: Entity 수정
  src/main/java/com/green/groupirum/domain/Member.java
  src/main/java/com/green/groupirum/domain/Recruit.java
Labels: backend, feature

#12 feat: H2 DB 더미 데이터 추가
  src/main/resources/application.yml
  src/main/resources/db/h2/data.sql
  src/main/resources/db/h2/schema.sql
Labels: backend, feature

#14 feat: 메인 페이지 모집글 출력, 메인 페이지 기능추가
  src/main/java/com/green/groupirum/controller/HomeController.java
  src/main/java/com/green/groupirum/domain/Game.java
  src/main/java/com/green/groupirum/dto/RecruitDto.java
  src/main/java/com/green/groupirum/service/RecruitService.java
  src/main/resources/static/css/Contact.css
  src/main/resources/static/css/nicepage.css
  src/main/resources/static/js/jquery.js
  src/main/resources/static/js/nicepage.js
  src/main/resources/templates/index.html
Labels: frontend, backend, feature

#16 feat: 모집글 상세보기 추가, 상세보기 페이지 생성
  src/main/java/com/green/groupirum/controller/RecruitController.java
  src/main/java/com/green/groupirum/service/RecruitService.java
  src/main/resources/static/css/nicepage.css
  src/main/resources/static/css/recruitView.css
  src/main/resources/static/images/reply.png
  src/main/resources/static/images/time.png
  src/main/resources/static/js/nicepageView.js
  src/main/resources/templates/index.html
  src/main/resources/templates/recruitView.html
Labels: frontend, backend, feature

#20 feat: head, header, footer 분리, html 코드 정리
  src/main/resources/static/css/contact.css
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/recruitView.html
Labels: frontend, feature

#21 feat: OAuth2 로그인 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/green/groupirum/auth/AuthMember.java
  src/main/java/com/green/groupirum/auth/AuthMemberDTO.java
  src/main/java/com/green/groupirum/auth/MemberLoginSuccessHandler.java
  src/main/java/com/green/groupirum/auth/MemberOAuth2UserService.java
  src/main/java/com/green/groupirum/auth/userinfo/GoogleUserInfo.java
  src/main/java/com/green/groupirum/auth/userinfo/KakaoUserInfo.java
  src/main/java/com/green/groupirum/auth/userinfo/NaverUserInfo.java
  src/main/java/com/green/groupirum/auth/userinfo/OAuth2UserInfo.java
  src/main/java/com/green/groupirum/config/SecurityConfig.java
  src/main/java/com/green/groupirum/controller/MemberController.java
  src/main/java/com/green/groupirum/controller/OAuthController.java
  src/main/java/com/green/groupirum/domain/Member.java
  src/main/java/com/green/groupirum/domain/MemberRole.java
  src/main/java/com/green/groupirum/dto/MemberDto.java
  src/main/java/com/green/groupirum/repository/MemberRepository.java
  src/main/java/com/green/groupirum/service/MemberService.java
  src/main/resources/application.yml
  src/main/resources/db/h2/data.sql
  src/main/resources/db/h2/schema.sql
  src/main/resources/static/css/join.css
  src/main/resources/static/css/login.css
  src/main/resources/static/images/google_login_button.png
  src/main/resources/static/images/kakao_login_button.png
  src/main/resources/static/images/naver_login_button.png
  src/main/resources/static/js/join.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/join.html
  src/main/resources/templates/login.html
Labels: frontend, backend, api, feature
